#ifndef _NETBASE_FRAMEWORK_CMDDISPATCHER_H_
#define _NETBASE_FRAMEWORK_CMDDISPATCHER_H_

#include <cstdint>
#include <memory.h>
#include <unordered_map>
#include <functional>
#include <string_view>

#include "Asio.h"
#include "Client.h"

#include "log/Log.h"

/*
* Class: CmdDispatcher
* Responsible for registering user defined commands, and dispatching/calling parsed commands.
* Contains the ParsedCmd struct which is the internal representation of a parsed command used by Naetbase.
* The ParsedCmd is created by an incoming parsed command generated by the parser which has its own struct.
*
*	Register: Registers a command handler within the system by its id
*	Dispatch: Calls the registered handlers by id using the client as context
*/
class CmdDispatcher
{
public:
	struct ParsedCmd
	{
		std::uint_least16_t cmdid;
		std::string_view data;
	};

	using CmdHandlerFn = std::function<asio::awaitable<void>(std::shared_ptr<Client>, const ParsedCmd &)>;

	CmdDispatcher(std::shared_ptr<Log> log);
	~CmdDispatcher();

	void Register(std::uint_least16_t cmdid, CmdHandlerFn fn);

	asio::awaitable<void> Dispatch(std::shared_ptr<Client> client, ParsedCmd parsedcmd);

private:
	std::unordered_map<std::uint_least16_t, CmdHandlerFn> handlers;

	std::shared_ptr<Log> log;
};

#endif
